# -*- coding: utf-8 -*- #

import os
import time
import unittest

from HTMLTestRunner import HTMLTestRunner
from selenium.webdriver.common.by import By
from utils.config import Config, DATA_PATH, REPORT_PATH, REPORT_PATH #import 一个类 一个常数 逗号分开
from utils.log import logger
from utils.file_reader import ExcelReader
from utils.mail import Email
from utils.generator import generator

from common.lenovo_main_page import LenovoMainPage
from common.info_page import InfoPage

#EXCEL = DATA_PATH + Config().get('xlsx').get("file_name")
#self.excel_datas = ExcelReader(self.EXCEL).data

def sendEmail():
    Email(  title   = Config().get('mail').get("title"),
    message = Config().get('mail').get("message"),
    receiver= Config().get('mail').get("receiver"),
    server  = Config().get('mail').get("server"),
    sender  = Config().get('mail').get("sender"),
    password= Config().get('mail').get("password"),
    path    = REPORT_PATH ).send()

if __name__ == '__main__':
    discover = unittest.defaultTestLoader.discover(start_dir='./testcases/',pattern='test_*.py')

    #这个可以直接在控制台看错误
    runner = unittest.TextTestRunner(verbosity=2)
    runner.run(discover)

    #
    # with open(REPORT_PATH, 'w') as f:
    #     runner = HTMLTestRunner(stream=f,
    #                             title='MathFunc Test Report',
    #                             description='generated by HTMLTestRunner.',
    #                             verbosity=2
    #                             )
    #     runner.run(discover)
    #
    # #注意 这个不能写在teardownclass里面，执行的时候html还没有生成
    #sendEmail()

